package com.post_hub.iam_service.mapper;

import com.post_hub.iam_service.model.dto.post.PostDTO;
import com.post_hub.iam_service.model.dto.post.PostSearchDTO;
import com.post_hub.iam_service.model.entities.Post;
import com.post_hub.iam_service.model.request.post.PostRequest;
import com.post_hub.iam_service.model.request.post.UpdatePostRequest;
import org.hibernate.type.descriptor.DateTimeUtils;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

import java.util.Objects;

@Mapper(
		componentModel = "spring",
		nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
		imports = {DateTimeUtils.class, Objects.class}
)
public interface PostMapper {
	// Just example of how @Mapping works, same name fields will be mapped automatically.
	@Mapping(source = "id", target = "id")
	@Mapping(source = "title", target = "title")
	@Mapping(source = "content", target = "content")
	@Mapping(source = "likes", target = "likes")
	@Mapping(source = "created", target = "created", dateFormat = "yyyy-MM-dd HH:mm:ss")
	PostDTO toPostDTO(Post post);

	// Ignore these because they are automatically generated by db.
	@Mapping(target = "id", ignore = true)
	@Mapping(target = "created", ignore = true)
	// No needs to create @Mapping for rest fields as their names matches
	Post createPost(PostRequest postRequest);

	@Mapping(target = "id", ignore = true)
	@Mapping(target = "created", ignore = true)
	void updatePost(@MappingTarget Post post, UpdatePostRequest request);

	@Mapping(source = "deleted", target = "isDeleted")
	PostSearchDTO toPostSearchDTO(Post post);
}
