spring.application.name=iam_service
server.servlet.context-path=/

server.port=8189

spring.datasource.url=jdbc:postgresql://localhost:5432/post_hub_local
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Default database schema for Hibernate
spring.jpa.properties.hibernate.default_schema=v1_iam_service
# Hibernate SQL dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Let Hibernate automatically update the schema (dev only, NOT migrations!)
spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=v1_iam_service

end.point.posts=/posts
end.point.id=/{id}
end.point.create=/create

logging.level.com.post_hub.iam_service=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.flywaydb=DEBUG
