spring.application.name=iam_service
server.servlet.context-path=/

server.port=8189

jwt.secret=CISeA6wgEpnKgCkyfagPOGobDhe3FwXiM7dRfIwWbLXAPlog5LJn5dZOEgI1r5c95BiPw1zA7/vylBKRkRlcBg==
jwt.lifetime=300000
jwt.expiration=1200000

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/post_hub_local
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Default database schema for Hibernate
spring.jpa.properties.hibernate.default_schema=v1_iam_service
# Hibernate SQL dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Let Hibernate automatically validate the schema.
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=v1_iam_service

end.point.posts=/posts
end.point.users=/users
end.point.comments=/posts/{postId}/comments

end.point.id=/{id}
end.point.all=/all
end.point.create=/create
end.point.search=/search

end.point.auth=/auth
end.point.login=/login
end.point.register=/register
end.point.refresh.token=/refresh/token

logging.level.com.post_hub.iam_service=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.flywaydb=DEBUG
